#This class is responsible for translating messages generated by resource_controller
# when a translation file defined in config/locales
# yml file structure:
# example in config/locales/pt-BR.yml:
# resource_controller:
#     messages:
#       successfully_removed: "Registro removido com sucesso!"  
#       successfully_update: "Registro alterado com sucesso!"
#       successfully_created: "Registro criado com sucesso!"
#       successfully_created: "Registro criado com sucesso!"
#       object_not_found: "Objeto não encontrado."

module ResourceController
  module I18n
      def translate(key, options = {})
        if defined?(::I18n)
          ::I18n.translate key, options
        else
          options[:default]
        end
      end      
      alias :t :translate
    end
  end
end

